Fix AttributeError with Pillow>=10: Downgrade to Pillow 9.3 for 'textsize' Compatibility
as latest version of pillow causing problem of 
AttributeError: 'ImageDraw' object has no attribute 'textsize'
downgrading the version of pillow to 9.3 fixes the problem